In [1]:
import numpy as np


In [2]:
a=np.arange(1000)

In [3]:
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [7]:
list1=np.array([1,2,3])
print(list1)

type(list1)

[1 2 3]


numpy.ndarray

In [6]:
list2=np.array((1,2,3))
list2

array([1, 2, 3])

In [10]:
list3=np.array(1,dtype=np.int64)
list3

array(1, dtype=int64)

In [11]:
list3.size

1

In [12]:
list4=np.array([1,2,3],dtype=np.float64)

In [13]:
list4

array([1., 2., 3.])

In [14]:
list5=np.array(42)
list5

array(42)

In [15]:
list5.size

1

In [16]:
#2 boyutlu numpy array

In [18]:
list5=np.array([[1,2,3],[10,20,30]])

In [19]:
list5.size

6

In [20]:
list5.shape

(2, 3)

In [31]:
b=np.arange(6)
b[np.newaxis:]

array([0, 1, 2, 3, 4, 5])

In [30]:
b[np.newaxis,:]

array([[0, 1, 2, 3, 4, 5]])

In [32]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [33]:
np.arange(1,30)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [37]:
np.zeros(4).reshape(2,2)

array([[0., 0.],
       [0., 0.]])

In [42]:

np.ones(10,dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [43]:
np.empty(5)

array([2.12199579e-314, 9.31556152e-312, 3.77466153e-321, 9.31556153e-312,
       9.33262686e-312])

In [52]:
np.linspace(0,10,11)#3 parametre bu aralıktan kaç sayı istendiğini gösterir ve aralık bu sayıya eşit olacak şekilde bölünür eş aralıklarla

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [59]:
c=np.arange(20,1,-2)

In [60]:
print(c)
c.sort()
c

[20 18 16 14 12 10  8  6  4  2]


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [62]:
e=np.arange(4,8)
d=np.arange(4)

In [63]:
e

array([4, 5, 6, 7])

In [64]:
d

array([0, 1, 2, 3])

In [66]:
np.concatenate((e,d))

array([4, 5, 6, 7, 0, 1, 2, 3])

In [67]:
d.size

4

In [69]:
d.ndim#boyut

1

In [70]:
d.shape


(4,)

In [76]:
g=d.reshape([2,2])

In [77]:
g.size

4

In [78]:
g.ndim

2

In [79]:
g.shape


(2, 2)

In [81]:
np.reshape(g ,newshape=(4,),order="C")

array([0, 1, 2, 3])

In [82]:
g

array([[0, 1],
       [2, 3]])

In [90]:
f=g.reshape(4,)

In [91]:
f[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3]])

In [93]:
f[np.newaxis,:]

array([[0, 1, 2, 3]])

In [94]:
f

array([0, 1, 2, 3])

In [95]:
#expand_dims aynı görevi yapıyor

In [96]:
np.expand_dims(f,axis=1)

array([[0],
       [1],
       [2],
       [3]])

In [97]:
np.expand_dims(f,axis=0)

array([[0, 1, 2, 3]])

In [98]:
#indexing and slicing

In [99]:
f

array([0, 1, 2, 3])

In [100]:
f[0:2]

array([0, 1])

In [102]:
f[-2:]

array([2, 3])

In [103]:
f


array([0, 1, 2, 3])

In [106]:
f[f>1]

array([2, 3])

In [107]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [111]:
a[a<7]

array([1, 2, 3, 4, 5, 6])

In [126]:
x=(a>7)
a[x]

array([ 8,  9, 10, 11, 12])

In [127]:
x

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [135]:
b=np.nonzero(a<7)
b

(array([0, 0, 0, 0, 1, 1], dtype=int64),
 array([0, 1, 2, 3, 0, 1], dtype=int64))

In [136]:
b[0]

array([0, 0, 0, 0, 1, 1], dtype=int64)

In [137]:
b[1]

array([0, 1, 2, 3, 0, 1], dtype=int64)

In [138]:
v=np.array([1,2,3,4])
h=np.array([5,6,7,8],dtype=np.int64)
t=list(zip(v,h))

In [139]:
t

[(1, 5), (2, 6), (3, 7), (4, 8)]

In [140]:
type(t[0][1])

numpy.int64

In [141]:
a[b]

array([1, 2, 3, 4, 5, 6])